const FLAVOR_TEXT = [
    "A flickering light in the abandoned Victoria’s Secret storefront pulses with an unnatural rhythm.",
    "Whispered voices ride the draft, too faint to decipher, but undeniably present.",
    "Claire swears she saw a fleeting shadow slink between racks of mannequins in Dillard’s.",
    "The piped-in Muzak from a long-dead intercom sputters back to life, playing a distorted, melancholic lullaby.",
    "Iridescent puddles form on otherwise dry floors, reflecting impossible angles and shifting images.",
    "A sudden gust slams a display window shut in an empty storefront, with no trace of force.",
    "An unsettled feeling lingers, like eyes watching from the collapsed upper levels of the mall.",
    "Glowing fungi sprout along the base of support pillars, casting an unnerving luminescence.",
    "The coos and flaps of unseen birds echo from the food court vents, interrupted by colossal, unnatural croaking.",
    "A misplaced plush near a play structure seems to twitch its eyepatch when no one is looking.",

    "Bloodstains smear a ripped movie poster in the old AMC theater, too aged to be recent.",
    "The muffled clang of metal against metal echoes from somewhere deep within the mall’s bowels.",
    "A makeshift barricade blocks an entrance hallway, hastily assembled from debris and rebar.",
    "Animal bones are arranged in a crude circle outside a Sephora storefront.",
    "Torn magazine pages on survival tactics litter a corridor, ending with an image of a bloodied hand clutching a knife.",
    "An overwhelming stench of decay clings to the air vents near the old Modell’s Sporting Goods.",
    "An overturned shopping cart spills designer boots across the floor, surrounded by tracks that are not human.",

    "Half-finished drawings abandoned near the children’s play area show stick figures trapped beneath a fading rainbow.",
    "A tattered wedding portrait rests inside a Claire’s display case, water-stained and nearly erased.",
    "Pleas for help are scrawled across boarded windows, the ink bleeding downward like tears.",
    "An overflowing diaper pail sits in the abandoned food court, radiating a cloying, accusatory silence.",
    "Stacks of unopened greeting cards at a Hallmark kiosk mock the present desolation with cheerful messages.",
    "A lonely teddy bear slumps against a clothing rack, threadbare and missing an eye.",
    "A faint lullaby plays through a tinny intercom deep within the mall, echoing lost innocence.",
    "A locket engraved with initials is found clutched in a pile of ash where a fire once burned.",
    "Graffiti on a boarded storefront reads ‘Gone Fishin’,’ a child’s worn fishing rod leaning nearby.",

    "A scavenger returns empty-handed, muttering about a guttural chant from the darkened wing of the mall.",
    "Wild animal corpses lie trapped behind collapsed display windows, their vacant eyes staring outward.",
    "A rhythmic thumping approaches like frantic footsteps, then stops abruptly, leaving only silence.",
    "Flickering emergency lights reveal mannequins twisted as if mid-struggle, feathers scattered among them.",
    "Radio interference crackles with fragments of panicked voices before dissolving into static.",
    "An abandoned backpack spills dusty picture books and a single untouched juice box onto the floor.",
    "Crude symbols painted in blood-red appear overnight near emergency exits, alien and unsettling.",
    "Discarded magazines lie open to fashion spreads beside survival gear ads, the contrast deeply wrong.",
    "An acrid metallic tang hangs near the Gap racks, with singed threads hinting at a desperate escape attempt.",

    "A collection of children's shoes, all different sizes, are neatly arranged on the fountain's edge.",
    "The scent of saltwater and brine permeates the air near the outdoor seating area, despite no visible ocean.",
    "A single, ornate birdcage hangs empty from a broken lamppost, its door ajar.",
    "A pile of tarnished silver jewelry lies scattered beneath a discarded promotional banner.",
    "Strange, geometric patterns have been etched into the pavement near the carousel.",
    "Empty, brightly colored balloons are tangled in the branches of a dead palm tree.",
    "A child's drawing of a monstrous figure is taped to a storefront window, rendered in crayon.",
    "The wind whistles through broken glass panels of an outdoor cafe, creating an eerie melody.",
    "A series of cryptic messages are written on the underside of a park bench.",
    "A collection of faded photographs, depicting smiling families, are glued to a wall.",

    "Overgrown weeds push through cracks in the concrete walkways, obscuring faded advertisements.",
    "A discarded child's mask lies face down in a puddle, its painted smile unsettling.",
    "The sound of dripping water echoes from within the fountain, despite it being dry.",
    "A circle of smooth, grey stones has been arranged on the asphalt near the entrance.",
    "A collection of broken toys and dolls are gathered in a corner beneath an awning.",
    "A tattered map of the area, marked with strange symbols, is found near a fountain.",
    "The air smells faintly of burnt sugar and something else… something organic.",
    "A single, antique key lies on the ground near a boarded-up store.",
    "Shadows seem to move independently in the periphery, even when no one is around.",
    "A swarm of unusually large insects buzzes around a broken sign advertising a long-closed ice cream parlor.",

    "A carousel horse lies on its side, its painted eyes staring blankly at the sky.",
    "Strange, unidentifiable footprints are pressed into the dusty ground near the fast food joint.",
    "The sound of faint music box melody drifts from within the closed fountain.",
    "A collection of oddly shaped rocks has been placed in a deliberate pattern on the sidewalk.",
    "A single, withered flower grows stubbornly through a crack in the pavement.",
    "A pile of old flyers advertising events that never happened is clustered near a doorway.",
    "The wind carries a faint scent of lavender and something metallic.",
    "A series of handprints, too small to be human, are smeared on a window.",
    "A strange humming sound vibrates through the ground, barely audible but persistent.",
    "A collection of mismatched buttons and trinkets is arranged in a circle on a bench.",

    "Dust motes dance in the shafts of moonlight, illuminating a stillness that feels like a tomb.",
    "Rusting metal and peeling paint are the only witnesses to a slow, inevitable decline.",
    "Even the shadows seem to weep in this forsaken place, clinging to the remnants of what once was.",
    "A profound emptiness permeates every corner, a void where joy and life have ceased to exist.",
    "The silence is not peaceful; it's the heavy weight of absence, pressing down on the soul.",
    "Here, time has stopped, leaving only the ghosts of memories and the despair of what remains.",
    "Hope is a forgotten word in this desolate landscape, replaced by the chilling certainty of oblivion." ,
    "The faint scent of decay clings to everything, a constant reminder of mortality's grim embrace.",
    "A distant, metallic screech echoes from the direction of the loading docks, quickly swallowed by the vastness.",
    "The scent of ozone hangs faintly in the air near the old tire shop, a lingering trace of electrical discharge.",
    "Scratches mar the freshly painted walls of a storefront, too deliberate to be accidental.",
    "A low, guttural growl vibrates through the floor, seemingly originating from within the abandoned parking garage.",
    "Faint, rhythmic impacts reverberate from the back of the food court, masked by the hum of the ventilation system.",
    "The shattered remains of a display case are not recent; the glass is fractured with unnatural force.",
    "A series of rapid, muffled thuds emanate from behind the boarded-up windows of a defunct electronics store.",
    "The air grows colder near the fountain, carrying a metallic tang that suggests spilled blood.",
    "Distorted shouts and cries drift faintly on the wind, quickly lost to the echoing emptiness.",
    "A sudden tremor shakes the ground, followed by a brief, sharp crack – like something breaking."
];